### PR TITLE
Runtime safety

### PR DESCRIPTION
**Pull request by shtukas**

### CODE REVIEW

**Comment by LATaylor-guardian** [comment]
👍

**Comment by LATaylor-guardian** [comment]
@shtukas This repo needs the github report status configuring in Team City.

**Comment by shtukas** [comment]
> This repo needs the github report status configuring in Team City.

Oh. Cool. I will do that!

**Comment by shtukas** [comment]
> This repo needs the github report status configuring in Team City.

Done!

**Pull request merged**
